import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowUp,
  Bean,
  Bell,
  Blocks,
  Boxes,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Dna,
  Download,
  Ellipsis,
  Eye,
  FlaskConical,
  Funnel,
  GitFork,
  GitMerge,
  Hash,
  History,
  Image,
  Info,
  LayoutDashboard,
  Leaf,
  Library,
  LogOut,
  Menu,
  Microscope,
  Moon,
  Network,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  Ruler,
  Search,
  Settings,
  SlidersHorizontal,
  Sprout,
  StickyNote,
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Trophy,
  UserRound,
  Users,
  X,
  ZoomIn,
  ZoomOut,
  Scan,
  type LucideProps,
} from "lucide-react";

// Single icon family (Lucide). Names are semantic so pages never import the
// library directly and the mapping stays consistent across the product.
const icons = {
  overview: LayoutDashboard,
  program: Sprout,
  pedigree: GitFork,
  phenotype: Microscope,
  inventory: Boxes,
  operations: CalendarClock,
  users: Users,
  bell: Bell,
  leaf: Leaf,
  image: Image,
  menu: Menu,
  add: Plus,
  edit: Pencil,
  archive: Archive,
  restore: ArchiveRestore,
  search: Search,
  filter: Funnel,
  inspect: Eye,
  close: X,
  settings: Settings,
  download: Download,
  history: History,
  trait: Tag,
  score: Trophy,
  calendar: CalendarClock,
  seed: Bean,
  plant: Sprout,
  parent: Sprout,
  cross: GitMerge,
  family: Network,
  lot: Package,
  module: Blocks,
  library: Library,
  setup: SlidersHorizontal,
  evaluation: ClipboardList,
  lineage: Dna,
  measure: Ruler,
  notes: StickyNote,
  activity: Activity,
  warning: TriangleAlert,
  info: Info,
  check: Check,
  up: ArrowUp,
  down: ArrowDown,
  remove: Trash2,
  more: Ellipsis,
  expand: ChevronDown,
  next: ChevronRight,
  code: Hash,
  lab: FlaskConical,
  sun: Sun,
  moon: Moon,
  logout: LogOut,
  profile: UserRound,
  collapse: PanelLeftClose,
  uncollapse: PanelLeftOpen,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fit: Scan,
} as const;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  size = 16,
  ...props
}: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return (
    <Component
      size={size}
      strokeWidth={1.75}
      aria-hidden="true"
      focusable="false"
      {...props}
    />
  );
}
